### 1. Read the dataset and check if anything missing

In [1]:
#import necessary modules to manipulate the datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#read training and test sets
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [3]:
train.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [4]:
test.describe()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,...,28000.000000,28000.000000,28000.000000,28000.000000,28000.000000,28000.0,28000.0,28000.0,28000.0,28000.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.164607,0.073214,0.028036,0.011250,0.006536,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.473293,3.616811,1.813602,1.205211,0.807475,0.0,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.000000,254.000000,193.000000,187.000000,119.000000,0.0,0.0,0.0,0.0,0.0

In [5]:
#find nan values
print(np.sum(np.sum(train.isnull(), axis = 1)))
print(np.sum(np.sum(test.isnull(), axis = 1)))

0
0

Every sample is a 28*28 img

The first column "label" ranges from 0 to 9, which also should be the output value

No missing/NaN values in the datasets

In [3]:
#set features and labels
features = train.iloc[:, 1:]
label = train.iloc[:, 0]

### 2. Try sklearn / machine learning

In [4]:
#import ML modules
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [8]:
#logistic regression
clf = GaussianNB()
clf.fit(features, label)

GaussianNB(priors=None)

In [9]:
clf.score(features, label)

0.55719047619047624

All other ML algorithms take a lot of time training.

And Gaussian got a horrible score.

There's no way implementing them without normalization and grouping

In [7]:
#import preprocessing module
from sklearn.preprocessing import MinMaxScaler
normalized_features = MinMaxScaler().fit_transform(features.loc[:, features.columns])
normalized_test = MinMaxScaler().fit_transform(test.loc[:, test.columns])

In [16]:
normalized_features.shape

(42000, 784)

In [19]:
clf.fit(normalized_features, label)
clf.score(normalized_features, label)

0.55571428571428572

In [6]:
import time

In [20]:
# Try LogisticRegression
print(time.asctime())
clf = LogisticRegression()
clf.fit(normalized_features, label)
print(clf.score(normalized_features, label))
print(time.asctime())

Tue Nov 28 22:22:07 2017
0.93080952381
Tue Nov 28 22:23:03 2017

In [29]:
#pretty good score
#first try on test and upload to Kaggle
#normalized_test = MinMaxScaler().fit_transform(test.loc[:, test.columns])
prediction = pd.DataFrame(clf.predict(normalized_test), columns = ['Label']).reset_index()

In [32]:
prediction.rename(columns = {'index': 'ImageId'}, inplace = True)
prediction.iloc[:, 0] += 1
prediction

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      7
4            5      3
5            6      7
6            7      0
7            8      3
8            9      0
9           10      3
10          11      5
11          12      7
12          13      4
13          14      0
14          15      4
15          16      3
16          17      3
17          18      1
18          19      9
19          20      0
20          21      9
21          22      1
22          23      1
23          24      5
24          25      7
25          26      4
26          27      2
27          28      7
28          29      7
29          30      7
...        ...    ...
27970    27971      5
27971    27972      0
27972    27973      4
27973    27974      8
27974    27975      0
27975    27976      3
27976    27977      6
27977    27978      0
27978    27979      1
27979    27980      9
27980    27981      3
27981    27982      1
27982    27983      8
27983    27984      0
27984    27985      4
27985    27986      5
27986    27987      2
27987    27988      2
27988    27989      1
27989    27990      6
27990    27991      7
27991    27992      6
27992    27993      1
27993    27994      4
27994    27995      7
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [34]:
prediction.to_csv('logisticML.csv', index = False)
#accuracy = 0.91642

In [10]:
#how about knn
#import time
print(time.asctime())
clf = KNeighborsClassifier()
clf.fit(normalized_features, label)
#print(clf.score(normalized_features, label)) #0.979142857143
print(time.asctime())

Tue Nov 28 23:30:10 2017
Tue Nov 28 23:30:23 2017

In [11]:
#even better!
#normalized_test = MinMaxScaler().fit_transform(test.loc[:, test.columns])
prediction = pd.DataFrame(clf.predict(normalized_test), columns = ['Label']).reset_index()
prediction.rename(columns = {'index': 'ImageId'}, inplace = True)
prediction.iloc[:, 0] += 1
prediction.to_csv('knnML.csv', index = False)
#0.96800
#but took a lot of time to predict!!!

In [10]:
#decision tree
print(time.asctime())
clf = DecisionTreeClassifier()
clf.fit(normalized_features, label)
print(clf.score(normalized_features, label))
print(time.asctime())

Wed Nov 29 02:16:47 2017
1.0
Wed Nov 29 02:16:58 2017

In [11]:
print(time.asctime())
prediction = pd.DataFrame(clf.predict(normalized_test), columns = ['Label']).reset_index()
prediction.rename(columns = {'index': 'ImageId'}, inplace = True)
prediction.iloc[:, 0] += 1
prediction.to_csv('dtML.csv', index = False)
print(time.asctime())
#0.85485 sucks

Wed Nov 29 02:16:58 2017
Wed Nov 29 02:16:58 2017

In [12]:
#random forest
print(time.asctime())
clf = RandomForestClassifier()
clf.fit(normalized_features, label)
print(clf.score(normalized_features, label))
print(time.asctime())

Wed Nov 29 02:18:08 2017
0.999404761905
Wed Nov 29 02:18:11 2017

In [13]:
print(time.asctime())
prediction = pd.DataFrame(clf.predict(normalized_test), columns = ['Label']).reset_index()
prediction.rename(columns = {'index': 'ImageId'}, inplace = True)
prediction.iloc[:, 0] += 1
prediction.to_csv('rfML.csv', index = False)
print(time.asctime())
#0.94000 no better

Wed Nov 29 02:18:23 2017
Wed Nov 29 02:18:23 2017

In [14]:
#SVC
print(time.asctime())
clf = SVC()
clf.fit(normalized_features, label)
print(clf.score(normalized_features, label))
print(time.asctime())

Wed Nov 29 02:19:34 2017
0.940523809524
Wed Nov 29 05:39:03 2017

In [15]:
print(time.asctime())
prediction = pd.DataFrame(clf.predict(normalized_test), columns = ['Label']).reset_index()
prediction.rename(columns = {'index': 'ImageId'}, inplace = True)
prediction.iloc[:, 0] += 1
prediction.to_csv('svcML.csv', index = False)
print(time.asctime())
#0.93585

Wed Nov 29 05:39:03 2017
Wed Nov 29 09:16:42 2017

In [16]:
#AdaBoost
print(time.asctime())
clf = AdaBoostClassifier()
clf.fit(normalized_features, label)
print(clf.score(normalized_features, label))
print(time.asctime())

Wed Nov 29 09:16:42 2017
0.737428571429
Wed Nov 29 09:17:07 2017

In [17]:
print(time.asctime())
prediction = pd.DataFrame(clf.predict(normalized_test), columns = ['Label']).reset_index()
prediction.rename(columns = {'index': 'ImageId'}, inplace = True)
prediction.iloc[:, 0] += 1
prediction.to_csv('adaML.csv', index = False)
print(time.asctime())
#guess it would not get over 0.9

Wed Nov 29 09:17:07 2017
Wed Nov 29 09:17:08 2017